# web port
server.port=8082

# log config
logging.config=classpath:logback.xml

# xxl-rpc
xxl-rpc.remoting.port=7080

script.file.home=d:/tmp/script
script.log.home=d:/tmp/log
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/